core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView

from .views import  IndexView

app_name = 'core'

urlpatterns = [
    
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:index'), name='logout'),


]

defe_orsm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('institucion.urls')),
    path('', include('persona.urls')),
    path('', include('expediente.urls')),
    path('', include('usuario.urls')),
    path('', include('profesional.urls')),
    #path('', include('internacion.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

institucion/urls.py
from django.urls import path
from django.contrib.auth import views

from .views import InstitucionCreateView

app_name = 'institucion'

urlpatterns = [
    path('institucion/nueva/', InstitucionCreateView.as_view(), name='institucion_create'),
    
]

persona/urls.py
from django.urls import path
from django.contrib.auth import views

from .views import PersonaCreateView

app_name = 'persona'

urlpatterns = [

    path('persona/nueva/', PersonaCreateView.as_view(), name='persona_create'),
    
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('institucion.urls')),
    path('', include('persona.urls')),
    path('', include('expediente.urls')),
    #path('', include('usuario.urls')),
    #path('', include('profesional.urls')),
    #path('', include('internacion.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
# cuentas/urls.py
from django.urls import path
from .views import PerfilUsuarioUpdateView, CambiarContrasenaView

app_name = 'usuario'

urlpatterns = [
    path('perfil/', PerfilUsuarioUpdateView.as_view(), name='editar_perfil'),
    path('cambiar-contrasena/', CambiarContrasenaView.as_view(), name='cambiar_contrasena'),
]

core/models.py
from django.db import models
#from django.contrib.auth.models import User
#Para nuestro modelo de usuario personalizado debemos
#importar setings y reemplaza el uso de User por settings.AUTH_USER_MODEL
from django.conf import settings




# Modelos para gestionar información de países, provincias, géneros, niveles educativos, tipos de documentos, sedes, localidades, áreas profesionales y profesiones.
# Estas tablas seran complatadas por el administrador del sistema para que los usuarios puedan seleccionar de una lista desplegable
# Sólo se permitirá crear registros de Localidades
class Pais(models.Model):
    pais = models.CharField(max_length=100, blank=True, null=True, verbose_name='País')

    def __str__(self):
        return self.pais
    
    class Meta:
        verbose_name = 'País'
        verbose_name_plural = 'Países'
        ordering = ['pais']



class Provincia(models.Model):
    provincia = models.CharField(max_length=100, verbose_name='Provincia', blank=True, null=True)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, verbose_name='País', blank=True, null=True, related_name='provincias_pais', default=None)

    def __str__(self):
        return self.provincia
    
    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'

    

class Genero(models.Model):
    genero = models.CharField('Genero', max_length=50, unique=True)
    
    def __str__(self):
        return self.genero

    class Meta:
        verbose_name='Genero'
        verbose_name_plural='Generos'



class Nivel_Educativo(models.Model):
    nivel_educativo = models.CharField('Nivel Educativo', max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.nivel_educativo

    class Meta:
        verbose_name='Nivel Educativo'
        verbose_name_plural='Niveles Educativos'



class Tipo_Documento(models.Model):
    tipo_documento = models.CharField('Tipo de documento', max_length=50)
    
    def __str__(self):
        return self.tipo_documento
    
    class Meta:
        verbose_name ='Tipo de documento'
        verbose_name_plural = 'Tipos de documentos'



class Localidad(models.Model):
    localidad = models.CharField(verbose_name='Localidad', max_length=70, blank=False, null=False)
    codigo_postal = models.CharField('Código de postal', max_length=50, blank=True, null=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE, verbose_name='Provincia', blank=True, null=True, related_name='localidades_provincia')


    def __str__(self):
        return self.localidad
    
    class Meta:
        unique_together = ('localidad', 'provincia')#no se pueden repetir localidades en la misma provincia
        verbose_name = 'Localidad'
        verbose_name_plural = 'Localidades'



class Sede(models.Model):
    sede = models.CharField('Sede', max_length=50)
    abreviatura = models.CharField('Nombre abreviado', max_length=4, blank=True, null=True, unique=True)
    telefono = models.CharField(max_length=20, verbose_name=("Teléfono"), blank=True, null=True)
    direccion_calle = models.CharField(max_length=50, verbose_name=("Calle"), blank=True, null=True)
    direccion_numero = models.CharField(max_length=10, verbose_name=("Número"), blank=True, null=True)
    direccion_piso = models.CharField(max_length=10, verbose_name=("Piso"), blank=True, null=True)
    direccion_depto = models.CharField(max_length=10, verbose_name=("Dto."), blank=True, null=True)
    localidad = models.ForeignKey(Localidad, on_delete=models.CASCADE, verbose_name='Localidad', blank=True, null=True, related_name='sede_localidad')
    
    def __str__(self):
        return self.sede
    
    class Meta:
        verbose_name ='Sede'
        verbose_name_plural = 'Sedes'



class AreaProfesional(models.Model):
    area_profesional = models.CharField('Área profesional', max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.area_profesional
    
    class Meta:
        verbose_name = 'Área profesional'
        verbose_name_plural = 'Áreas profesionales'



class Profesion (models.Model):
    profesion = models.CharField('Profesión', max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.profesion
    
    class Meta:
        verbose_name = 'Profesión'
        verbose_name_plural = 'Profesiones'

core/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import TemplateView



class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'core/index.html'
    login_url = 'core:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Bienvenido a DEFE-ORSM'
        return context

templates/core/include/base.html
{% load static %}

<!doctype html>
<html lang="es">

{% block head %}
  <!--begin::Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% block title %}<title>AdminLTE 4 | General Form Elements</title>{% endblock title %}
    <!--begin::Accessibility Meta Tags-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
    <meta name="color-scheme" content="light dark" />
    <meta name="theme-color" content="#007bff" media="(prefers-color-scheme: light)" />
    <meta name="theme-color" content="#1a1a1a" media="(prefers-color-scheme: dark)" />
    <!--end::Accessibility Meta Tags-->
    <!--begin::Primary Meta Tags-->
    <meta name="title" content="AdminLTE 4 | General Form Elements" />
    <meta name="author" content="ColorlibHQ" />
    <meta
      name="description"
      content="AdminLTE is a Free Bootstrap 5 Admin Dashboard, 30 example pages using Vanilla JS. Fully accessible with WCAG 2.1 AA compliance."
    />
    <meta
      name="keywords"
      content="bootstrap 5, bootstrap, bootstrap 5 admin dashboard, bootstrap 5 dashboard, bootstrap 5 charts, bootstrap 5 calendar, bootstrap 5 datepicker, bootstrap 5 tables, bootstrap 5 datatable, vanilla js datatable, colorlibhq, colorlibhq dashboard, colorlibhq admin dashboard, accessible admin panel, WCAG compliant"
    />
    <!--end::Primary Meta Tags-->
    <!--begin::Accessibility Features-->
    <!-- Skip links will be dynamically added by accessibility.js -->
    <meta name="supported-color-schemes" content="light dark" />
    <link rel="preload" href="{% static '/AdminLTE-4.0.0-rc4/css/adminlte.css' %}" as="style" />
    <!--end::Accessibility Features-->
    <!--begin::Fonts-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fontsource/source-sans-3@5.0.12/index.css"
      integrity="sha256-tXJfXfp6Ewt1ilPzLDtQnJV4hclT9XuaZUKyUvmyr+Q="
      crossorigin="anonymous"
      media="print"
      onload="this.media='all'"
    />
    <!--end::Fonts-->
    <!--begin::Third Party Plugin(OverlayScrollbars)-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.11.0/styles/overlayscrollbars.min.css"
      crossorigin="anonymous"
    />
    <!--end::Third Party Plugin(OverlayScrollbars)-->
    <!--begin::Third Party Plugin(Bootstrap Icons)-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
      crossorigin="anonymous"
    />
    <!--end::Third Party Plugin(Bootstrap Icons)-->
    <!--begin::Required Plugin(AdminLTE)-->
    
    
    <link rel="stylesheet" href="{% static '/AdminLTE-4.0.0-rc4/css/adminlte.css' %}" />
    <!--end::Required Plugin(AdminLTE)-->

    <link href="{% static 'css/expedientes.css' %}" rel="stylesheet">

     {% block extra_head %}
       
     {% endblock extra_head %} 

  </head>
  <!--end::Head-->
{% endblock head %}

  <!--begin::Body-->
  <body class="layout-fixed sidebar-expand-lg sidebar-open bg-body-tertiary">
    <!--begin::App Wrapper-->
    <div class="app-wrapper">

      
      {% block nav-header %}
        {% include 'core/include//top_bar.html' %}
      {% endblock nav-header %}

      
      {% block side-bar %}
        {% include 'core/include//side-bar.html' %}
      {% endblock side-bar %}

      
      {% block content %}
      <!--begin::App Main-->
      <main class="app-main">
        <!--begin::App Content Header-->
        <div class="app-content-header">
          <!--begin::Container-->
          <div class="container-fluid">

          {% block first_row_body %}
            
          {% endblock first_row_body %}
          
          </div>
          <!--end::Container-->
        </div>
        <!--end::App Content Header-->
        <!--begin::App Content-->
        <div class="app-content">
          <!--begin::Container-->
          <div class="container-fluid">
            
            {% block body %}
            
            {% endblock body %}
              
          </div>
          <!--end::Container-->
        </div>
        <!--end::App Content-->
      </main>
      <!--end::App Main-->
      {% endblock content %}
      
      
      {% block footer %}
      <!--begin::Footer-->
      <footer class="app-footer">
       
        <!--begin::Copyright-->
        <strong>
          Copyright &copy; 1991-2025&nbsp;
          <a href="https://defensoriasantafe.gob.ar" class="text-decoration-none">Defensoría del Pueblo - Provincia de Santa Fe</a>.
        </strong>
        All rights reserved.
        <!--end::Copyright-->
      </footer>
      <!--end::Footer-->
      {% endblock footer %}

    </div>
    <!--end::App Wrapper-->

  {% block js_page %}

    <!--begin::Script-->
    <!--begin::Third Party Plugin(OverlayScrollbars)-->
    <script
      src="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.11.0/browser/overlayscrollbars.browser.es6.min.js"
      crossorigin="anonymous"
    ></script>
    <!--end::Third Party Plugin(OverlayScrollbars)--><!--begin::Required Plugin(popperjs for Bootstrap 5)-->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      crossorigin="anonymous"
    ></script>
    <!--end::Required Plugin(popperjs for Bootstrap 5)--><!--begin::Required Plugin(Bootstrap 5)-->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js"
      crossorigin="anonymous"
    ></script>
    <!--end::Required Plugin(Bootstrap 5)--><!--begin::Required Plugin(AdminLTE)-->
    <script src="{% static '/AdminLTE-4.0.0-rc4/js/adminlte.js' %}"></script>
    <!--end::Required Plugin(AdminLTE)--><!--begin::OverlayScrollbars Configure-->
    <script>
      const SELECTOR_SIDEBAR_WRAPPER = '.sidebar-wrapper';
      const Default = {
        scrollbarTheme: 'os-theme-light',
        scrollbarAutoHide: 'leave',
        scrollbarClickScroll: true,
      };
      document.addEventListener('DOMContentLoaded', function () {
        const sidebarWrapper = document.querySelector(SELECTOR_SIDEBAR_WRAPPER);
        if (sidebarWrapper && OverlayScrollbarsGlobal?.OverlayScrollbars !== undefined) {
          OverlayScrollbarsGlobal.OverlayScrollbars(sidebarWrapper, {
            scrollbars: {
              theme: Default.scrollbarTheme,
              autoHide: Default.scrollbarAutoHide,
              clickScroll: Default.scrollbarClickScroll,
            },
          });
        }
      });
    </script>
    <!--end::OverlayScrollbars Configure-->
    <!--end::Script-->
    {% endblock js_page %}
  </body>


  <!--end::Body-->
</html>

templates/core/include/side-bar.html
{% load static %}

<!--begin::Sidebar-->
      <aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="light">
        <!--begin::Sidebar Brand-->
        <div class="sidebar-brand">
          <!--begin::Brand Link-->
          <a href="../index.html" class="brand-link">
            <!--begin::Brand Image-->
            <img
              src="{% static '/AdminLTE-4.0.0-rc4/assets/img/AdminLTELogo.png'%}"
              alt="AdminLTE Logo"
              class="brand-image opacity-75 shadow"
            />
            <!--end::Brand Image-->
            <!--begin::Brand Text-->
            <span class="brand-text fw-light">AdminLTE 4</span>
            <!--end::Brand Text-->
          </a>
          <!--end::Brand Link-->
        </div>
        <!--end::Sidebar Brand-->
        <!--begin::Sidebar Wrapper-->
        <div class="sidebar-wrapper">
          <nav class="mt-2">
            <!--begin::Sidebar Menu-->
            <ul
              class="nav sidebar-menu flex-column"
              data-lte-toggle="treeview"
              role="navigation"
              aria-label="Main navigation"
              data-accordion="false"
              id="navigation"
            >
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-speedometer"></i>
                  <p>
                    Expedientes
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="../index.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Medio de ingreso</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../index2.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Listado</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../index3.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Agregar documentos</p>
                    </a>
                  </li>
                </ul>
              </li>
          
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-box-seam-fill"></i>
                  <p>
                    Personas
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'persona:persona_create' %}" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Nueva</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../widgets/info-box.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Listado</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../widgets/cards.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Cards</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-clipboard-fill"></i>
                  <p>
                    Profesionales
                    <span class="nav-badge badge text-bg-secondary me-3"></span>
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="../layout/unfixed-sidebar.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Nuevo</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../layout/fixed-sidebar.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Listado</p>
                    </a>
                  </li>
                  
                  <li class="nav-item">
                    <a href="../layout/logo-switch.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Sidebar Mini <small>+ Logo Switch</small></p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../layout/layout-rtl.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Layout RTL</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-tree-fill"></i>
                  <p>
                    Instituciones
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'institucion:institucion_create' %}" class="nav-link active">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Nueva</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../UI/icons.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Nueva</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../UI/timeline.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Timeline</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="nav-icon bi bi-pencil-square"></i>
                  <p>
                    Internaciones
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'institucion:institucion_create' %}" class="nav-link active">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Nueva</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../UI/icons.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Nueva</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../UI/timeline.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Timeline</p>
                    </a>
                  </li>
                </ul>
              </li>
              
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-table"></i>
                  <p>
                    Calendario
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="../tables/simple.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Simple Tables</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-header">STAFF</li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-box-arrow-in-right"></i>
                  <p>
                    Administración
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="/admin/" class="nav-link">
                      <i class="nav-icon bi bi-box-arrow-in-right"></i>
                      <p>
                        Admin
                        <i class="nav-arrow bi bi-chevron-right"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="../examples/login.html" class="nav-link">
                          <i class="nav-icon bi bi-circle"></i>
                          <p>Login</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="../examples/register.html" class="nav-link">
                          <i class="nav-icon bi bi-circle"></i>
                          <p>Register</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="nav-icon bi bi-box-arrow-in-right"></i>
                      <p>
                        Version 2
                        <i class="nav-arrow bi bi-chevron-right"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="../examples/login-v2.html" class="nav-link">
                          <i class="nav-icon bi bi-circle"></i>
                          <p>Login</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="../examples/register-v2.html" class="nav-link">
                          <i class="nav-icon bi bi-circle"></i>
                          <p>Register</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a href="../examples/lockscreen.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Lockscreen</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-header">DOCUMENTATIONS</li>
              
              
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-ui-checks-grid"></i>
                  <p>
                    Components
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="../docs/components/main-header.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Main Header</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="../docs/components/main-sidebar.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Main Sidebar</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon bi bi-filetype-js"></i>
                  <p>
                    Javascript
                    <i class="nav-arrow bi bi-chevron-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="../docs/javascript/treeview.html" class="nav-link">
                      <i class="nav-icon bi bi-circle"></i>
                      <p>Treeview</p>
                    </a>
                  </li>
                </ul>
              </li>
              
            </ul>
            <!--end::Sidebar Menu-->
          </nav>
        </div>
        <!--end::Sidebar Wrapper-->
      </aside>
      <!--end::Sidebar-->

templates/core/include/top_bar.html
{% load static %}
<!--begin::Header-->
      <nav class="app-header navbar navbar-expand bg-body">
        <!--begin::Container-->
        <div class="container-fluid">
          <!--begin::Start Navbar Links-->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
                <i class="bi bi-list"></i>
              </a>
            </li>
            <li class="nav-item d-none d-md-block"><a href="{% url 'core:index' %}" class="nav-link">Inicio</a></li>
            <li class="nav-item d-none d-md-block"><a href="#" class="nav-link">Contact</a></li>
          </ul>
          <!--end::Start Navbar Links-->
          <!--begin::End Navbar Links-->
          <ul class="navbar-nav ms-auto">

            <!--begin::Fullscreen Toggle-->
            <li class="nav-item">
              <a class="nav-link" href="#" data-lte-toggle="fullscreen">
                <i data-lte-icon="maximize" class="bi bi-arrows-fullscreen"></i>
                <i data-lte-icon="minimize" class="bi bi-fullscreen-exit" style="display: none"></i>
              </a>
            </li>
            <!--end::Fullscreen Toggle-->

            <!--begin::User Menu Dropdown-->
            <li class="nav-item dropdown user-menu">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                {% if user.foto_perfil %}
                <img
                  src="{{ user.foto_perfil.url }}"
                  class="user-image rounded-circle shadow"
                  alt="User Image"
                />
                {% else %}
                <img
                  src="{% static 'AdminLTE-4.0.0-rc4/assets/img/avatar.png' %}"
                  class="user-image rounded-circle shadow"
                  alt="User Image"
                />
                {% endif %}
                
                <span class="d-none d-md-inline">{{ user.first_name }} {{ user.last_name }}</span>
              </a>
              
              {% block user %}
              <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                    <!--begin::User Image-->
                    <li class="user-header text-bg-primary">
                        
                            {% if user.foto_perfil and user.foto_perfil.url %}
                                <img src="{{ user.foto_perfil.url }}"
                                    class="user-image rounded-circle shadow mt-2"
                                    alt="User Image"
                                />
                            {% else %}
                                <img src="{% static 'AdminLTE-4.0.0-rc4/assets/img/avatar.png' %}"
                                    class="user-image rounded-circle shadow"
                                    alt="User Image"
                                />
                            {% endif %}
                        
                        
                        <div class="row">
                            <p>
                                <small>{{ user.first_name }} {{ user.last_name }} - {{ profesional.profesion }}</small>
                            </p>
                            <p>
                                <small>Usuario desde - {{ user.date_joined|date:"M. Y" }}</small>
                            </p>
                        </div>
                        
                    </li>
                    <!--end::User Image-->
                    <!--begin::Menu Body-->
                    <li class="user-body">
                        <!--begin::Row-->
                        <div class="row">
                            <div class="btn btn-default btn-flat">
                                <a href="{% url 'usuario:editar_perfil' %}">Perfil</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="btn btn-default btn-flat">
                                <a href="{% url 'usuario:cambiar_contrasena' %}">Actualizar contraseña</a>
                            </div>
                        </div>
                        <!--end::Row-->
                    </li>
                    <!--end::Menu Body-->
                    <!--begin::Menu Footer-->
                    <li class="user-footer">
                        <form action="{% url 'core:logout' %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link">Cerrar sesión</button>
                        </form>
                    </li>
                    <!--end::Menu Footer-->
                </ul>
              {% endblock user %}  

            </li>
            <!--end::User Menu Dropdown-->
          </ul>
          <!--end::End Navbar Links-->
        </div>
        <!--end::Container-->
      </nav>
      <!--end::Header-->